### ISSUE TITLE
VNC doesn't work

### ISSUE THREAD

**Issue by WillNilges** [ComputerScienceHouse/proxstar#123]
The VNC functionality has been broken for years. It'd be really cool if it wasn't that way anymore.

It looks like some kind of issue with Redis. Need to dig into the logs more to see what I can extract, but here's what the VNC pod itself is saying.

```
2021-12-16 11:50:45,532 INFO creating SSH tunnel to proxmox12.csh.rit.edu for VM 118
[2021-12-16 11:52:40 -0500] [1] [CRITICAL] WORKER TIMEOUT (pid:30)
[2021-12-16 11:52:40 -0500] [30] [INFO] Worker exiting (pid: 30)
[2021-12-16 11:52:41 -0500] [46] [INFO] Booting worker with pid: 46
```

**Comment by Mstrodl** [comment]
Guess: we aren't completing our ssh and can't set the vnc parameters (sidenote, what if the monitor console commands have changed? it has been SEVERAL major versions since this was written)

Reposting this from Slack, if someone could try using websockify's actual python api and a websocket library we could support multiple clients with far less Jank

**Comment by WillNilges** [comment]
![image](https://user-images.githubusercontent.com/42927786/175202438-072c7c5f-e61e-44de-8c70-91cd7d490a0b.png)
Investigating this, I have no idea what's going on. It seems like it would definitely be possible to do away with the secondary proxstar-vnc container (which seems to just be running another instance of proxstar? IDK it's weird look at the gunicorn file).

**Comment by WillNilges** [comment]
https://pypi.org/project/websockets/ ?
